services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /media/USBHDD/share/docker/jellyfin/library:/config
      - /media/USBHDD/share/tv:/data/tvshows
      - /media/USBHDD/share/movies:/data/movies
      - /media/USBHDD/share/music:/music	
    ports:
      - 8096:8096
    restart: unless-stopped

  
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /media/USBHDD/share/docker/prowlarr/data:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /media/USBHDD/share/docker/radarr/data:/config
      - /media/USBHDD/share/movies:/movies
      - /media/USBHDD/share/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /media/USBHDD/share/docker/sonarr/data:/config
      - /media/USBHDD/share/tv:/tv
      - /media/USBHDD/share/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /media/USBHDD/share/docker/lidar/config:/config
      - /media/USBHDD/share/music:/music
      - /media/USBHDD/share/downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped


  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /media/USBHDD/share/docker/transmission/data:/config
      - /media/USBHDD/share/downloads:/downloads
      - /media/USBHDD/share/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - /media/USBHDD/share/docker/homarr/configs:/app/data/configs
      - /media/USBHDD/share/docker/homarr/icons:/app/public/icons
      - /media/USBHDD/share/docker/homarr/data:/data
    ports:
      - '7575:7575'

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    volumes:
      - /media/USBHDD/share/:/srv
      - /media/USBHDD/share/docker/filebrowser/filebrowser.db:/database/filebrowser.db
      - /media/USBHDD/share/docker/filebrowser/settings.json:/config/settings.json
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 8095:80 

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /media/USBHDD/share/docker/heimdall/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
